version: "3.7"

services:
    postgresql:
        image: jenkins/postgres:v1
        environment:
            POSTGRES_PASSWORD: Pp123456789
        networks:
            - project
        ports:
            - "5432:5432"
        # volumes:
        #     - phpvol:/var/lib/mysql
    nodejs:
        image: jenkins/nodejs:v1
        restart: always
        environment:
            SERVER_PORT: 5000
            DB_USER: postgres
            DB_PASSWORD: Pp123456789
            DB_NAME: techprotodo
            DB_HOST: postgresql
            DB_PORT: 5432
        depends_on:
            - postgresql
        ports:
            - "5000:5000"
        networks:
            - project
    react:
        image: jenkins/react:v1
        restart: always
        environment:
            REACT_APP_BASE_URL: http://54.84.222.183:5000/
        depends_on:
            - postgresql
        ports:
            - "3000:3000"
        networks:
            - project

networks:
    project:
        driver: bridge

# volumes:
#     phpvol:


# docker-compose up
# VOLUME EKLENECEK