---
- name: Execute shell commands on another EC2 instance
  hosts: _Jenkins_Project_Docker
  gather_facts: no

  tasks:
    - name: Run shell commands
      become: yes
      shell:
        cmd: |
          cd /usr/jenkins/workspace/Jenkins-Project/apps
          docker-compose up