---
- name: Execute shell commands on another EC2 instance
  hosts: _Jenkins-Project-Docker
  gather_facts: no

  tasks:
    - name: Run shell commands
      become: yes
      shell:
        cmd: |
          echo "Hello from {{ ansible_host }}"