version: "3.7"

services:
    database:
        image: mydata:1.0
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
        networks:
            - phpnet
        ports:
            - "3306:3306"
        volumes:
            - phpvol:/var/lib/mysql
    myapp:
        image: myapp:1.0
        restart: always
        environment:
            DATABASE_HOST: database
            DATABASE_NAME: mydatabase
            DATABASE_USERNAME: techpro
            DATABASE_PASSWORD: 123456789
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - phpnet

networks:
    phpnet:
        driver: bridge

volumes:
    phpvol:
